name: msc_device_image
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.1
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  mobile_scanner: ^6.0.5
  qr_code_scanner_plus: ^2.0.10+1
  qr_mobile_vision: ^5.0.2
  get: ^4.6.6
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  http: ^1.2.2
  get_storage: ^2.1.1
  http_parser: ^4.1.2
  shimmer: ^3.0.0
  loading_animation_widget:


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/logo/

  fonts:
    - family: Schyler
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
